source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
group :development do
  gem 'spring'
  gem 'quiet_assets'
  gem "letter_opener"
end

group :development, :test do
  gem 'pry'
  gem 'awesome_print'
end

group :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'timecop'
end

gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'devise'
gem 'simple_form'
gem 'execjs'
gem 'rest-client'
gem 'jpbuilder'
gem 'admin_view'
gem 'ransack'
gem 'kaminari'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-linkedin'
gem 'omniauth-google-oauth2'
gem 'omniauth-github'
gem 'omniauth-reddit', :git => 'git://github.com/jackdempsey/omniauth-reddit.git'
gem 'omniauth-weibo-oauth2'
# gem 'weibo_2'
gem 'omniauth-qq-oauth2', :git => 'git://github.com/dapic/omniauth-qq-oauth2.git'
gem 'mina'

gem 'activeadmin', github: 'activeadmin'
gem 'haml-rails'
gem 'gibbon'
gem 'fakeweb'
gem 'sidekiq'
gem 'exception_notification', github: 'smartinez87/exception_notification'
gem 'devise-i18n'
gem 'aasm'
gem 'clockwork'
